# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Your current directory:
    pwd
    echo all the files in the directory
    ls -lrt
    echo your hostname is:
    hostname
    
  displayName: 'Run a multi-line script'
